"""Embed skills/jev/SKILL.md and hooks/alert-hook.sh into jev.py (so `uv tool install` ships them).

Run after editing either file:  python scripts/sync_assets.py      (CI fails if they drift)"""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = (root / "jev.py").read_text()
start, end = src.index("# <assets>"), src.index("# </assets>")
block = ("# <assets> - generated by scripts/sync_assets.py from skills/jev/SKILL.md and hooks/alert-hook.sh\n"
         f"SKILL_MD = {(root / 'skills/jev/SKILL.md').read_text()!r}  # noqa: E501\n"
         f"HOOK_SH = {(root / 'hooks/alert-hook.sh').read_text()!r}  # noqa: E501\n")
new = src[:start] + block + src[end:]
if new != src:
    (root / "jev.py").write_text(new)
    print("jev.py updated")
else:
    print("assets already in sync")
